export default {
  provenance:
    "Generated before migration by Node crypto and the adapters at ec3ab388e912222012005be6de14d939e697ec59 (Noble hashes 2.3.0, ciphers 2.1.1). Inputs and envelope authority are retained below.",
  password: {
    password: "é\ud800!",
    pbkdf2: "pbkdf2-sha256$17$bGVnYWN5LXNhbHQtMTIzNA$G6DIqCrTwV_TumfknthZodZjO3d2YD2LILNzWM3Qe8E",
    phc: "$argon2id$v=19$m=32,t=2,p=1$bGVnYWN5LXNhbHQtMTIzNA$IoAj2o4dyDdM7d97dCo1roxF/iIOsyXJWjYO3uxkHwo",
  },
  totp: {
    key: "BwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwc",
    secret: "MTIzNDU2Nzg5MDEyMzQ1Njc4OTA",
    binding: {
      moduleId: "totp",
      subjectId: "subject",
      credentialId: "credential",
      revision: "rev1",
    },
    envelope: {
      keyId: "key1",
      revision: "rev1",
      nonce: "AwMDAwMDAwMDAwMD",
      ciphertext: "FMyQN28eaXpDcHJu2GPKOtoE2d8AdUKKUueXVvwh9CDEPWtn",
    },
    recovery: "rc1-00112233-44556677-8899AABB-CCDDEEFF",
    digest: "YDZEBf4XTEdCk6fNZkWduCE6N9HQTvGXGB7Trn-QEEs",
  },
  oauth: {
    key: "BwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwc",
    signIn: {
      context: {
        namespace: "effect-auth/oauth-sign-in-context/v1",
        moduleId: "oauth",
        generation: 1,
        flowId: "flow",
        commandId: "command",
        provider: "provider",
        protocol: "oidc",
        configurationGeneration: 1,
        issuer: "https://issuer.example",
        responseIssuerMode: "required",
        callbackId: "callback",
        redirectUri: "https://app.example/callback",
        returnTarget: "/",
        stateDigest: "BwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwc",
        requestBindingVerifier: "BwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwc",
        requestBindingExpiresAtMillis: 50000,
        issuedAtMillis: 1000,
        expiresAtMillis: 40000,
        claimLifetimeMillis: 10000,
      },
      plain: {
        namespace: "effect-auth/oauth-transaction-secrets/v1",
        state: "AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE",
        pkceVerifier: "AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgI",
        oidcNonce: "AwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwM",
      },
      sealed: {
        format: "oauth-xchacha20poly1305-v1",
        keyId: "key1",
        nonce: "vE9IiGO6i5gSUXgIX19RLQt5MrYOsFHa",
        ciphertext:
          "7iGgZkOUePwqqXH7zsCoTGlYw53dIpKz7NxfB12_wDI-G6QgBmPmV_dL5AVLm7LGotReVznjoZc1-5X-aAeZBX5bUMIujMHIFy0lGlXIdkfTqhzfZvlAy677ApLCrcmypiG12wx5s8zjoJ2XuBXrUv0pFBu4zrnsaw91Zd1QmtjT3vEZFDBc3vWsingwBTSmj3i_ls6-ETlTSrbgGtB5J7oEnCHfTTrxje0gnLO2-1dsacxGXz3JEjFgggrQW3eIHBcAIJh4M_TS69dr428pBLxc7mUVnT_EpRbiGWr1d1djqA_FDLHQVL-4OnZZ8iaQCJItp90",
      },
    },
    link: {
      context: {
        namespace: "effect-auth/oauth-link-context/v1",
        moduleId: "oauth",
        generation: 1,
        flowId: "flow",
        commandId: "command",
        provider: "provider",
        protocol: "oidc",
        configurationGeneration: 1,
        issuer: "https://issuer.example",
        responseIssuerMode: "required",
        callbackId: "callback",
        redirectUri: "https://app.example/callback",
        returnTarget: "/",
        stateDigest: "BwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwc",
        requestBindingVerifier: "BwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwc",
        requestBindingExpiresAtMillis: 50000,
        issuedAtMillis: 1000,
        expiresAtMillis: 40000,
        claimLifetimeMillis: 10000,
        revision: {
          subjectId: "subject",
          securityRevision: "rev1",
          credentials: [
            {
              credentialId: "credential",
              revision: "rev1",
            },
          ],
        },
        maximumEvidenceAgeMillis: 60000,
      },
      plain: {
        namespace: "effect-auth/oauth-transaction-secrets/v1",
        state: "AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE",
        pkceVerifier: "AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgI",
        oidcNonce: "AwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwM",
      },
      sealed: {
        format: "oauth-xchacha20poly1305-v1",
        keyId: "key1",
        nonce: "DwgjC3P7rNuTDyc944ZqW1yzdutWYsdf",
        ciphertext:
          "H954OAPG0vGcgu5O3dH2XtcP7nvUsDEkJdyYnozi8RVkuAPV4qJlkEZz0ngwCUeWEOhSZXYLvs_BM4wuwCBZejJf1o-07Km98sCxAtHBGl6FCz0fcckogjWjn5J5Q7L8Q8LPC-9nEuQrRdgSAiiUqqxLq3Sjufd06Qy8CROCTeecPTW0N_qaxzNuJrw48TlRKxdTWzyPd63Ary_qWQOl1IynKd_lsYkMPOfuisqBWht9M8MtqIEjBAb_MEmqlLNaH4aTaUk7182z1rCvxjPNO4H5z6NTNq_fZZI6DUOOubfFEMZwNfuPj9_6_QgKJvdHfrloqHs",
      },
    },
    connected: {
      context: {
        namespace: "effect-auth/oauth-connected-context/v1",
        moduleId: "oauth",
        generation: 1,
        flowId: "flow",
        commandId: "command",
        provider: "provider",
        protocol: "oidc",
        configurationGeneration: 1,
        issuer: "https://issuer.example",
        responseIssuerMode: "required",
        callbackId: "callback",
        redirectUri: "https://app.example/callback",
        returnTarget: "/",
        stateDigest: "BwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwc",
        requestBindingVerifier: "BwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwc",
        requestBindingExpiresAtMillis: 50000,
        issuedAtMillis: 1000,
        expiresAtMillis: 40000,
        claimLifetimeMillis: 10000,
        revision: {
          subjectId: "subject",
          securityRevision: "rev1",
          credentials: [
            {
              credentialId: "credential",
              revision: "rev1",
            },
          ],
        },
        profile: {
          key: "read",
          generation: 1,
          issuance: "active",
          provider: "provider",
          clientRegistrationId: "client",
          scopes: ["openid"],
          resources: [],
          retention: "access-and-refresh",
          maximumAccessLifetimeMillis: 3600000,
          maximumRefreshLifetimeMillis: 86400000,
          refreshAheadMillis: 30000,
          refresh: "confidential",
          revocation: "unsupported",
        },
        grantId: "grant",
        maximumEvidenceAgeMillis: 60000,
      },
      plain: {
        namespace: "effect-auth/oauth-transaction-secrets/v1",
        state: "AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE",
        pkceVerifier: "AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgI",
        oidcNonce: "AwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwM",
        authorizationUrl:
          "https://issuer.example/authorize?state=AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE",
      },
      sealed: {
        format: "oauth-xchacha20poly1305-v1",
        keyId: "key1",
        nonce: "UumM-stnEjKdNUyWJbq1FRm5lGd_ZBMy",
        ciphertext:
          "URHLK6ivllaAuqcfBCTgWQH0w_qlPlxVosC64k0pzqp6Y5Bwaq-3R9Y9yXhg4hEPbEB0znXFQMJU88YfQLyvIAkv_aRs03hcc07wFa9kZaHtr8WwnWN3CRKZ_CWq9FYOrOM79RZTIoX-R3rrCfx2_3Hb4B6QkXPD-loLBpxvcqVRY2Z0ZuSKxQv5aMgr3aJEaxvxAX2a03DFcDEuUK3OLUqP6f1k8NoM95mdD_XzAPw9K1cupZaqYv3TGbzIcvIP1f2Q7tkqyaG0hafRL8FX4UwhAtVeLGyq2Q8WGTt7XEmyq39n0aeNHUmFl-K8S-6SrsnExGaXUPvA4_P0WbC_wwuaz1CARvdQ3lNq4Ym0n4cwSvfxaYyTpRZmoaUDedghg9f5JRuaMN9k6lbKEryYPlDJ5gOb7L5G6TUWMK5P8BKc7XXj5csHXq1nbMZIruf9DQTclvtb4CDv-NivNg",
      },
    },
    token: {
      context: {
        namespace: "effect-auth/oauth-connected-token-context/v1",
        exchangeOrder: "1",
        moduleId: "oauth",
        subjectId: "subject",
        identity: {
          provider: "provider",
          issuer: "https://issuer.example",
          subject: "external",
        },
        configuration: {
          provider: "provider",
          protocol: "oidc",
          configurationGeneration: 1,
          issuer: "https://issuer.example",
          responseIssuerMode: "required",
          callbackId: "callback",
          redirectUri: "https://app.example/callback",
          profile: {
            key: "read",
            generation: 1,
            issuance: "active",
            provider: "provider",
            clientRegistrationId: "client",
            scopes: ["openid"],
            resources: [],
            retention: "access-and-refresh",
            maximumAccessLifetimeMillis: 3600000,
            maximumRefreshLifetimeMillis: 86400000,
            refreshAheadMillis: 30000,
            refresh: "confidential",
            revocation: "unsupported",
          },
        },
        grantId: "grant",
        grantVersion: "1",
        tokenVersion: "1",
        cohortGeneration: "1",
        metadata: {
          scopes: ["openid"],
          resources: [],
          accessExpiresAtMillis: 40000,
          useUntilMillis: 30000,
          obtainedAtMillis: 1000,
        },
      },
      plain: {
        namespace: "effect-auth/oauth-connected-token-material/v1",
        accessToken: "access",
        refreshToken: "refresh",
        continuation: {
          _tag: "Oidc",
          clientId: "client",
          nonce: "AwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwM",
          authTime: 1,
        },
      },
      sealed: {
        format: "oauth-connected-xchacha20poly1305-v1",
        keyId: "key1",
        nonce: "44L3lU7PCPaLhukiZYc25YYAmzI6LcEr",
        ciphertext:
          "GgmwqVtw-B7UoLEPSN7BZCjo7ZnE_6TA3Qj0-r2AEZw62BXPGhuRwahDptcMJdLoSCt9s2ovP6ObPXkrzpGdOrHFsLR5BRDV5EEfHaOAW3U4pQffAcZaD6ApCks3mPJ_JeQIez9wcvNCut4Um6IhpTVM6Ym0JtCYqg0DQ3gDM2zMYDtlcbc_q0WQZP73eExJJ6sax2trn2uVIWdC5AZ8Evo7h687ceEI7IufECXpjA9z_69oEjRJ-50r7NGyZn8MWvd-b8ScdxNgBzJah7nalIdRrgJl4DQKHDKlu666k0ZD61nRLSZnFYbd5nICT8PjtaYz",
      },
    },
  },
} as const;
