import { it } from "@effect/vitest";
import { Kdf } from "@yielded/crypto/Kdf";
import * as KdfAdmission from "@yielded/crypto/KdfAdmission";
import * as Portable from "@yielded/crypto/Portable";
import { Effect, Layer, Redacted, Schema } from "effect";
import { Hex } from "effect/encoding";
import { expect } from "vite-plus/test";

import { argon2Vectors, nativeArgon2Vectors } from "./fixtures/argon2-vectors";

const bytes = Schema.decodeSync(Schema.Uint8ArrayFromHex);

const layer = Portable.layer(globalThis.crypto.subtle, {
  maximumMemoryKiB: 262144,
  maximumMemoryPasses: 524288,
}).pipe(Layer.provide(KdfAdmission.layer({ concurrency: 2 })));

// Explicit upstream-suite request, before the owned implementation. All v19
// Argon2id known answers are retained; Argon2d/i and v16 are outside this API.
for (const vector of argon2Vectors) {
  it.effect(
    `Noble Argon2id v19 vector ${vector.sourceIndex}: m=${vector.m}, t=${vector.t}, p=${vector.p}`,
    () =>
      Effect.gen(function* () {
        const kdf = yield* Kdf;
        const password = bytes(vector.passwordHex);
        const salt = bytes(vector.saltHex);

        const derived = yield* kdf.argon2id({
          password: Redacted.make(password),
          salt,
          ...(vector.secretHex === undefined
            ? {}
            : { secret: Redacted.make(bytes(vector.secretHex)) }),
          ...(vector.dataHex === undefined ? {} : { associatedData: bytes(vector.dataHex) }),
          memoryKiB: vector.m,
          parallelism: vector.p,
          passes: vector.t,
          length: 32,
        });

        expect(Hex.encode(Redacted.value(derived))).toBe(vector.expectedHex);
        expect(Hex.encode(password)).toBe(vector.passwordHex);
        expect(Hex.encode(salt)).toBe(vector.saltHex);
      }).pipe(Effect.provide(layer)),
    { timeout: 30000 },
  );
}

// Independently generated by Node's native Argon2 before porting Noble's code.
// These fill the upstream suite's H' output-length and memory-rounding gaps.
for (const vector of nativeArgon2Vectors) {
  it.effect(`Argon2id native reference: ${vector.id}`, () =>
    Effect.gen(function* () {
      const kdf = yield* Kdf;

      const derived = yield* kdf.argon2id({
        password: Redacted.make(bytes(vector.passwordHex)),
        salt: bytes(vector.saltHex),
        memoryKiB: vector.m,
        parallelism: vector.p,
        passes: vector.t,
        length: vector.length,
      });

      expect(Hex.encode(Redacted.value(derived))).toBe(vector.expectedHex);
    }).pipe(Effect.provide(layer)),
  );
}

it.effect("keeps concurrent portable Argon2 work independent across scheduler yields", () =>
  Effect.gen(function* () {
    const kdf = yield* Kdf;

    const outputs = yield* Effect.forEach(
      argon2Vectors.filter((vector) => vector.m === 256),
      (vector) =>
        kdf
          .argon2id({
            password: Redacted.make(bytes(vector.passwordHex)),
            salt: bytes(vector.saltHex),
            memoryKiB: vector.m,
            parallelism: vector.p,
            passes: vector.t,
            length: 32,
          })
          .pipe(Effect.map((result) => [Hex.encode(Redacted.value(result)), vector.expectedHex])),
      { concurrency: 2 },
    );

    for (const [actual, expected] of outputs) expect(actual).toBe(expected);
  }).pipe(Effect.provide(layer)),
);
