// Selected and reformatted independent vectors; not generated by the code under test.
// See ../THIRD_PARTY_NOTICES.md for adaptation details and licenses.
// Wycheproof: Copyright 2016–2026 The Wycheproof Authors, Apache-2.0.
// Noble test influences: Copyright (c) 2022 Paul Miller, MIT.
// Each source URL pins the original result or standard section.

export const hmacVectors = [
  {
    hash: "SHA-1",
    keyHex: "0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b",
    messageHex: "4869205468657265",
    expectedHex: "b617318655057264e28bc0b6fb378c8ef146be00",
    source: "https://www.rfc-editor.org/rfc/rfc2202.html#section-3",
  },
  {
    hash: "SHA-256",
    keyHex: "0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b",
    messageHex: "4869205468657265",
    expectedHex: "b0344c61d8db38535ca8afceaf0bf12b881dc200c9833da726e9376c2e32cff7",
    source: "https://www.rfc-editor.org/rfc/rfc4231.html#section-4.2",
  },
  {
    hash: "SHA-384",
    keyHex: "0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b",
    messageHex: "4869205468657265",
    expectedHex:
      "afd03944d84895626b0825f4ab46907f15f9dadbe4101ec682aa034c7cebc59cfaea9ea9076ede7f4af152e8b2fa9cb6",
    source: "https://www.rfc-editor.org/rfc/rfc4231.html#section-4.2",
  },
  {
    hash: "SHA-512",
    keyHex: "0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b",
    messageHex: "4869205468657265",
    expectedHex:
      "87aa7cdea5ef619d4ff0b4241a1d6cb02379f4e2ce4ec2787ad0b30545e17cdedaa833b7d6b8a702038b274eaea3f4e4be9d914eeb61f1702e696c203a126854",
    source: "https://www.rfc-editor.org/rfc/rfc4231.html#section-4.2",
  },
] as const;

export const hkdfVector = {
  id: "hkdf-rfc5869-a1",
  algorithm: "HKDF",
  hash: "SHA-256",
  ikmHex: "0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b",
  saltHex: "000102030405060708090a0b0c",
  infoHex: "f0f1f2f3f4f5f6f7f8f9",
  lengthBytes: 42,
  expectedHex:
    "3cb25f25faacd57a90434f64d0362f2a2d2d0a90cf1a5a4c5db02d56ecc4c5bf34007208d5b887185865",
  source: "https://www.rfc-editor.org/rfc/rfc5869.html#appendix-A.1",
  why: "Nonempty distinct salt/info and output beyond one hash block catch argument order and length conversion.",
} as const;

export const pbkdf2Vectors = [
  {
    id: "pbkdf2-rfc7914-80000",
    algorithm: "PBKDF2",
    hash: "SHA-256",
    passwordHex: "50617373776f7264",
    saltHex: "4e61436c",
    iterations: 80000,
    lengthBytes: 64,
    expectedHex:
      "4ddcd8f60b98be21830cee5ef22701f9641a4418d04c0414aeff08876b34ab56a1d425a1225833549adb841b51c9b3176a272bdebba1d078478f62b397f33c8d",
    source: "https://www.rfc-editor.org/rfc/rfc7914.html#section-11",
    why: "Two output blocks; the 80000 iteration vector additionally detects ignored iteration count. Prefer 80000 alone if choosing only one.",
  },
  {
    id: "pbkdf2-binary-password",
    algorithm: "PBKDF2",
    hash: "SHA-256",
    passwordHex: "7061737300776f7264ff",
    saltHex: "73616c7400c3a9",
    iterations: 2,
    lengthBytes: 32,
    source: "https://docs.python.org/3/library/hashlib.html#hashlib.pbkdf2_hmac",
    why: "NUL and invalid UTF-8 bytes must not be decoded, normalized or truncated.",
    expectedHex: "413e155d1bff9c3fa04ad04545494ac47748ed088b778a3437f78b69b56b35f9",
  },
] as const;

export const argon2Vector = {
  id: "argon2id-rfc9106-5.3",
  algorithm: "Argon2id",
  version: 19,
  passwordHex: "0101010101010101010101010101010101010101010101010101010101010101",
  saltHex: "02020202020202020202020202020202",
  secretHex: "0303030303030303",
  associatedDataHex: "040404040404040404040404",
  memoryKiB: 32,
  iterations: 3,
  parallelism: 4,
  lengthBytes: 32,
  expectedHex: "0d640df58d78766c08c037a34a8b53c9d01ef0452d75b65eb52520e96b01e659",
  source: "https://www.rfc-editor.org/rfc/rfc9106.html#section-5.3",
  referenceSource:
    "https://github.com/P-H-C/phc-winner-argon2/blob/f57e61e19229e23c4445b85494dbf7c07de721cb/kats/argon2id",
  why: "Distinguishes v19, id variant, KiB memory units, lanes, secret and AD mappings across native and Noble Layers.",
} as const;

export const aeadVectors = [
  {
    id: "aes256-gcm-wycheproof-91",
    algorithm: "AES-256-GCM",
    keyHex: "92ace3e348cd821092cd921aa3546374299ab46209691bc28b8752d17f123c20",
    nonceHex: "00112233445566778899aabb",
    aadHex: "00000000ffffffff",
    plaintextHex: "00010203040506070809",
    ciphertextHex: "e27abdd2d2a53d2f136b",
    tagHex: "9a4a2579529301bcfb71c78d4060f52c",
    sealedHex: "e27abdd2d2a53d2f136b9a4a2579529301bcfb71c78d4060f52c",
    source:
      "https://github.com/C2SP/wycheproof/blob/3fa63dd0344abb611f1fb1d77e119938603ea230/testvectors_v1/aes_gcm_test.json",
    alsoInNoble:
      "https://github.com/paulmillr/noble-ciphers/blob/785181b0772ba84afbe812025714163e4e48262f/test/vectors/wycheproof/aes_gcm_test.json",
    tcId: 91,
    why: "Exactly 256-bit key, 12-byte nonce, 16-byte tag; nonempty AAD and short plaintext prove appended-tag framing and authentication.",
  },
  {
    id: "xchacha20poly1305-draft03-a3.1",
    algorithm: "XChaCha20-Poly1305",
    keyHex: "808182838485868788898a8b8c8d8e8f909192939495969798999a9b9c9d9e9f",
    nonceHex: "404142434445464748494a4b4c4d4e4f5051525354555657",
    aadHex: "50515253c0c1c2c3c4c5c6c7",
    plaintextHex:
      "4c616469657320616e642047656e746c656d656e206f662074686520636c617373206f66202739393a204966204920636f756c64206f6666657220796f75206f6e6c79206f6e652074697020666f7220746865206675747572652c2073756e73637265656e20776f756c642062652069742e",
    ciphertextHex:
      "bd6d179d3e83d43b9576579493c0e939572a1700252bfaccbed2902c21396cbb731c7f1b0b4aa6440bf3a82f4eda7e39ae64c6708c54c216cb96b72e1213b4522f8c9ba40db5d945b11b69b982c1bb9e3f3fac2bc369488f76b2383565d3fff921f9664c97637da9768812f615c68b13b52e",
    tagHex: "c0875924c1c7987947deafd8780acf49",
    sealedHex:
      "bd6d179d3e83d43b9576579493c0e939572a1700252bfaccbed2902c21396cbb731c7f1b0b4aa6440bf3a82f4eda7e39ae64c6708c54c216cb96b72e1213b4522f8c9ba40db5d945b11b69b982c1bb9e3f3fac2bc369488f76b2383565d3fff921f9664c97637da9768812f615c68b13b52ec0875924c1c7987947deafd8780acf49",
    source: "https://www.ietf.org/archive/id/draft-irtf-cfrg-xchacha-03.html#appendix-A.3.1",
    alsoInNoble:
      "https://github.com/paulmillr/noble-ciphers/blob/785181b0772ba84afbe812025714163e4e48262f/test/vectors/stablelib_xchacha20poly1305.json",
    why: "Independent published 24-byte nonce AEAD vector; catches accidental use of ordinary ChaCha20-Poly1305 and lost AAD.",
  },
] as const;

export const signatureVectors = [
  {
    algorithm: "ECDSA-P256-SHA256",
    messageHex: "313233343030",
    signatureHex:
      "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    publicKeySpkiHex:
      "3059301306072a8648ce3d020106082a8648ce3d030107034200042927b10512bae3eddcfe467828128bad2903269919f7086069c8c4df6c732838c7787964eaac00e5921fb1498a60f4606766b3d9685001558d1a974e7341513e",
    expectedValid: false,
    source:
      "https://github.com/C2SP/wycheproof/blob/3fa63dd0344abb611f1fb1d77e119938603ea230/testvectors_v1/ecdsa_secp256r1_sha256_p1363_test.json",
  },
  {
    algorithm: "RSA-PSS-SHA256",
    messageHex: "",
    signatureHex:
      "4f01e0c12b08625ecac89a69231906edf826380f37c959a96690d046316d68ffce9d5c471694fcebfc6b45534864689256e4fc81c78e583f675d0c94b449647451e81beff01a11a516d5e5ce3f1a910437cb8a3a5096b19fb15f4524a35b23d89cdba12cf5b71aac1047b28c562df7c5542c34ce23a182cf7e0e231934b17294799d44877a1d68ef1b8f073619b7618e6b7c22db20030d98cf591ffc3d4da5f58613ecd5ecfc3b40a1d02f40891ca43695cd4c088b05a8054c89c595a47e274816f35384226f74459ee63e25a1bfc03c360490552ec38343f8ace502f065303b00bc0ec320711b211fde92e57feb9013c3609342495ec0d7cabdec21e54acc38",
    publicKeySpkiHex:
      "30820122300d06092a864886f70d01010105000382010f003082010a0282010100a2b451a07d0aa5f96e455671513550514a8a5b462ebef717094fa1fee82224e637f9746d3f7cafd31878d80325b6ef5a1700f65903b469429e89d6eac8845097b5ab393189db92512ed8a7711a1253facd20f79c15e8247f3d3e42e46e48c98e254a2fe9765313a03eff8f17e1a029397a1fa26a8dce26f490ed81299615d9814c22da610428e09c7d9658594266f5c021d0fceca08d945a12be82de4d1ece6b4c03145b5d3495d4ed5411eb878daf05fd7afc3e09ada0f1126422f590975a1969816f48698bcbba1b4d9cae79d460d8f9f85e7975005d9bc22c4e5ac0f7c1a45d12569a62807d3b9a02e5a530e773066f453d1f5b4c2e9cf7820283f742b9d50203010001",
    expectedValid: true,
    source:
      "https://github.com/C2SP/wycheproof/blob/3fa63dd0344abb611f1fb1d77e119938603ea230/testvectors_v1/rsa_pss_2048_sha256_mgf1_32_test.json",
  },
  {
    algorithm: "RSASSA-PKCS1-v1_5-SHA256",
    messageHex: "",
    signatureHex:
      "840f5dac53106dd1f9c57219224cf51289290c42f20466875ba8e830ac5690e541536fcc8ab03b731f82bf66d83f194e7e180b3963ec7a2f3f7904a7ce49aed47da4d4b79421eaf937d301b3e696169297b797c32c076a12be4de0b58e003c5123051a84a10c62f8dac2f42a8640008eb3c7cccd6760ff5b51b689763922582845f048fb8150e5a7a6ca2eccc7bdc85349ad5b26c52137a79fa3fe5c29ab5cd7615013219c1941b6708e9c3c23feff5febaf0c8ebca5750b54e3e6e99a3e876b396f27860b7f3ec4e9191703c6332d944f6f69751167680c79c4f6b57f1cc8755d24b6ec158ccdbacdb23107a33cb6b332516c13274d1f9dccc21dced869e486",
    publicKeySpkiHex:
      "30820122300d06092a864886f70d01010105000382010f003082010a0282010100a2b451a07d0aa5f96e455671513550514a8a5b462ebef717094fa1fee82224e637f9746d3f7cafd31878d80325b6ef5a1700f65903b469429e89d6eac8845097b5ab393189db92512ed8a7711a1253facd20f79c15e8247f3d3e42e46e48c98e254a2fe9765313a03eff8f17e1a029397a1fa26a8dce26f490ed81299615d9814c22da610428e09c7d9658594266f5c021d0fceca08d945a12be82de4d1ece6b4c03145b5d3495d4ed5411eb878daf05fd7afc3e09ada0f1126422f590975a1969816f48698bcbba1b4d9cae79d460d8f9f85e7975005d9bc22c4e5ac0f7c1a45d12569a62807d3b9a02e5a530e773066f453d1f5b4c2e9cf7820283f742b9d50203010001",
    expectedValid: true,
    source:
      "https://github.com/C2SP/wycheproof/blob/3fa63dd0344abb611f1fb1d77e119938603ea230/testvectors_v1/rsa_signature_2048_sha256_test.json",
  },
  {
    algorithm: "RSASSA-PKCS1-v1_5-SHA256",
    messageHex: "313233343030",
    signatureHex:
      "4b140acb262c451b0761236b926afa2829e8a095828f7dcf196eaf7fa46fdcf7fbcaf194aa3000ae8d3dc7dacc26952502b1558a67fb692da5fcc7dbf48cbc5260e2b2a7041fdf7bf46f531d4ef48998dfcb65e182065535aaf182ae6abf6e819e7d96ec86178137a3c14383f89438ab35f0dc7698e1811c415e163f8bac5435dddba5db55aa6b393d538d31b34332fcc34ef8e6eb059d4cc453297d6895ba480593a5536a4e553a55417295b6f6798734df67e739e54d3092de4f476cc0f65aac6950631081df1116097a7f6a9d00a1afbe0ce6b2bd32ef22acc95219f05df9fb7e9a8b391e6277cffeda298bf094730f5663172183dc5842056de36137ee90",
    publicKeySpkiHex:
      "30820122300d06092a864886f70d01010105000382010f003082010a0282010100a2b451a07d0aa5f96e455671513550514a8a5b462ebef717094fa1fee82224e637f9746d3f7cafd31878d80325b6ef5a1700f65903b469429e89d6eac8845097b5ab393189db92512ed8a7711a1253facd20f79c15e8247f3d3e42e46e48c98e254a2fe9765313a03eff8f17e1a029397a1fa26a8dce26f490ed81299615d9814c22da610428e09c7d9658594266f5c021d0fceca08d945a12be82de4d1ece6b4c03145b5d3495d4ed5411eb878daf05fd7afc3e09ada0f1126422f590975a1969816f48698bcbba1b4d9cae79d460d8f9f85e7975005d9bc22c4e5ac0f7c1a45d12569a62807d3b9a02e5a530e773066f453d1f5b4c2e9cf7820283f742b9d50203010001",
    expectedValid: false,
    source:
      "https://github.com/C2SP/wycheproof/blob/3fa63dd0344abb611f1fb1d77e119938603ea230/testvectors_v1/rsa_signature_2048_sha256_test.json",
  },
  {
    algorithm: "Ed25519",
    messageHex: "",
    signatureHex:
      "e5564300c360ac729086e2cc806e828a84877f1eb8e5d974d873e065224901555fb8821590a33bacc61e39701cf9b46bd25bf5f0595bbe24655141438e7a100b",
    publicKeySpkiHex:
      "302a300506032b6570032100d75a980182b10ab7d54bfed3c964073a0ee172f3daa62325af021a68f707511a",
    expectedValid: true,
    source: "https://www.rfc-editor.org/rfc/rfc8032.html#section-7.1",
  },
  {
    algorithm: "ECDSA-P256-SHA256",
    messageHex: "33393439343031323135",
    signatureHex:
      "bfab3098252847b328fadf2f89b95c851a7f0eb390763378f37e90119d5ba3ddbdd64e234e832b1067c2d058ccb44d978195ccebb65c2aaf1e2da9b8b4987e3b",
    publicKeySpkiHex:
      "3059301306072a8648ce3d020106082a8648ce3d030107034200042927b10512bae3eddcfe467828128bad2903269919f7086069c8c4df6c732838c7787964eaac00e5921fb1498a60f4606766b3d9685001558d1a974e7341513e",
    expectedValid: true,
    source:
      "https://github.com/C2SP/wycheproof/blob/3fa63dd0344abb611f1fb1d77e119938603ea230/testvectors_v1/ecdsa_secp256r1_sha256_p1363_test.json",
  },
  {
    algorithm: "RSA-PSS-SHA256",
    messageHex: "",
    signatureHex:
      "20081f8894a1330c4d503f642880e3c30e398fc6235c24f1be752e2d49cd9493ac0cf999e275c4f89ff08f0d9ba4e264a332525a616d336bd9e822f41ab3f4fae2f48ec66c2e52642ed93b7cb944396fbaa727cbfdfc1f20aace99a6f2a74475c338f8d9f22a38cb5bc51752076503b3aef1e65e5a8f8583d9ae7378ded038cf516898ad06beb90a42b85764526fcea44f74258fa4efb1da253d337f65619181ceb832dfe285ce78ae6b15f204e23bab274e87445d9f5df97f41dc8e3a97736b62591d075744b2552f90bcf1b1393e1e7627ef1f985f2bbabd52e43a35d0ddf4c67126e391f922ef7b1bb1911cd6e1b303cb2910dd70672bbfb62ea4eaad725c",
    publicKeySpkiHex:
      "30820122300d06092a864886f70d01010105000382010f003082010a0282010100a2b451a07d0aa5f96e455671513550514a8a5b462ebef717094fa1fee82224e637f9746d3f7cafd31878d80325b6ef5a1700f65903b469429e89d6eac8845097b5ab393189db92512ed8a7711a1253facd20f79c15e8247f3d3e42e46e48c98e254a2fe9765313a03eff8f17e1a029397a1fa26a8dce26f490ed81299615d9814c22da610428e09c7d9658594266f5c021d0fceca08d945a12be82de4d1ece6b4c03145b5d3495d4ed5411eb878daf05fd7afc3e09ada0f1126422f590975a1969816f48698bcbba1b4d9cae79d460d8f9f85e7975005d9bc22c4e5ac0f7c1a45d12569a62807d3b9a02e5a530e773066f453d1f5b4c2e9cf7820283f742b9d50203010001",
    expectedValid: false,
    source:
      "https://github.com/C2SP/wycheproof/blob/3fa63dd0344abb611f1fb1d77e119938603ea230/testvectors_v1/rsa_pss_2048_sha256_mgf1_0_test.json",
  },
] as const;

export const ed25519PrivateKeyHex =
  "302e020100300506032b6570042204209d61b19deffd5a60ba844af492ec2cc44449c5697b326919703bac031cae7f60" as const;
