/** Application-owned PostgreSQL schema. Apply once to a fresh Studio database. */
export const migrations = [
  'create table "studio_passkey_subject" ("id" uuid not null primary key, "status" text not null, "securityRevision" text not null, "name" text not null, "organization" text not null, "totpEnabled" boolean not null, "joinedAt" timestamp with time zone not null)',
  'create table "studio_passkey_factor" ("subjectId" uuid not null, "credentialId" text not null primary key, "revision" text not null, "status" text not null)',
  'create table "studio_passkey_credential" ("credentialId" text not null primary key, "subjectId" uuid not null, "rpId" text not null, "protocolCredentialId" text not null, "credentialKey" text not null unique, "userHandle" text not null, "publicKey" text not null, "algorithm" bigint not null, "profile" text not null, "credentialRevision" text not null, "status" text not null, "primarySignIn" boolean not null, "enrollmentUserVerified" boolean not null, "backupEligible" boolean not null, "backupState" boolean not null, "counter" bigint not null, "name" text not null, "createdAt" timestamp with time zone not null, "lastUsedAt" timestamp with time zone)',
  'create table "studio_passkey_flow" ("moduleId" text not null, "flowId" text not null primary key, "purpose" text not null, "snapshot" text not null, "applicationSnapshot" text, "requestBindingVerifier" text not null, "requestBindingExpiresAt" timestamp with time zone not null, "issuedAt" timestamp with time zone not null, "expiresAt" timestamp with time zone not null)',
  'create table "studio_login_flows" ("flowId" text not null primary key, "subjectId" uuid not null, "state" text not null, "pendingDigest" text, "dedupUntil" timestamp with time zone not null)',
  'create table "studio_pending_logins" ("digest" text not null primary key, "version" text not null, "flowId" text not null unique, "subjectId" uuid not null, "bindingDigest" text not null, "expiresAt" timestamp with time zone not null, "attemptLimit" integer not null, "failedAttempts" integer not null, "consumed" boolean not null, "payload" text not null)',
  'create table "studio_sessions" ("sessionId" text not null primary key, "subjectId" uuid not null, "digest" text not null unique, "version" text not null, "securityRevision" text not null, "issuedAt" timestamp with time zone not null, "expiresAt" timestamp with time zone not null, "absoluteExpiresAt" timestamp with time zone not null, "credentialVersion" text not null, "authenticatedAt" timestamp with time zone not null, "payload" text not null)',
  'create table "studio_authenticators" ("scope" text not null primary key, "state" text not null, "version" text not null)',
  'create table "studio_step_up" ("digest" text not null primary key, "version" text not null, "flowId" text not null unique, "subjectId" uuid not null, "bindingDigest" text not null, "snapshot" text not null, "expiresAt" timestamp with time zone not null, "attemptLimit" integer not null, "failedAttempts" integer not null, "consumed" boolean not null)',
  'create table "studio_registration_events" ("id" text not null primary key, "snapshot" text not null)',
] as const;
